# The goal for this project is to analyze data to help our developers understand what type of apps are likely to attract more users

In [1]:
import pandas as pd 

df=pd.read_csv('googleplaystore.csv') #import the data as a dataframe

df.dtypes # obtain the data type for each column

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [2]:
#df.describe()
df.head() #View a sample of the data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [3]:
df.shape

(10841, 13)

In [4]:
df["Reviews"] = df["Reviews"].apply(pd.to_numeric, errors = 'coerce') #convert reviews column to numeric

In [5]:
df.describe() #obtain a description of the numeric data columns. The output shows there are corrupt or invalid 
#values in the Rating column. So we drop them.

            Rating       Reviews
count  9367.000000  1.084000e+04
mean      4.193338  4.441529e+05
std       0.537431  2.927761e+06
min       1.000000  0.000000e+00
25%       4.000000  3.800000e+01
50%       4.300000  2.094000e+03
75%       4.500000  5.477550e+04
max      19.000000  7.815831e+07

In [6]:
df.dropna(subset=['Rating'], inplace=True) #drop all the Nan entries in Rating Column, use inplace to retain original
#dataframe name

In [7]:
df.describe()

            Rating       Reviews
count  9367.000000  9.366000e+03
mean      4.193338  5.140498e+05
std       0.537431  3.144042e+06
min       1.000000  1.000000e+00
25%       4.000000  1.862500e+02
50%       4.300000  5.930500e+03
75%       4.500000  8.153275e+04
max      19.000000  7.815831e+07

In [8]:
df.shape

(9367, 13)

In [9]:
#To convert the Installs column into numeric, convert from obj to str, remove + and , characters and drop NA
df['Installs'] = df['Installs'].astype('str')
df['Installs'] = df['Installs'].str.replace('+','')
df['Installs'] = df['Installs'].str.replace(',','')
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')
df.dropna(subset=['Installs'], inplace=True)

In [10]:
#Review appearance of data
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,10000.0,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,500000.0,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,5000000.0,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,50000000.0,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,100000.0,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [11]:
#Review shape of data, note that one more row is now removed.
df.shape

(9366, 13)

In [12]:
#check the data for inconsistencies
df.describe()

            Rating       Reviews      Installs
count  9366.000000  9.366000e+03  9.366000e+03
mean      4.191757  5.140498e+05  1.789744e+07
std       0.515219  3.144042e+06  9.123822e+07
min       1.000000  1.000000e+00  1.000000e+00
25%       4.000000  1.862500e+02  1.000000e+04
50%       4.300000  5.930500e+03  5.000000e+05
75%       4.500000  8.153275e+04  5.000000e+06
max       5.000000  7.815831e+07  1.000000e+09

In [13]:
#Isolate all the free apps by keeping all the rows where price is equal to 0
df = df[df.Price == '0']

In [14]:
df.describe()

            Rating       Reviews      Installs
count  8719.000000  8.719000e+03  8.719000e+03
mean      4.186203  5.511243e+05  1.921717e+07
std       0.512338  3.255360e+06  9.442960e+07
min       1.000000  1.000000e+00  1.000000e+00
25%       4.000000  2.370000e+02  1.000000e+04
50%       4.300000  7.816000e+03  1.000000e+06
75%       4.500000  9.653850e+04  5.000000e+06
max       5.000000  7.815831e+07  1.000000e+09

In [15]:
#Identify that there are some duplicate apps, with the only difference being number of reviews
df[df.App == 'Instagram']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2545,Instagram,SOCIAL,4.5,66577313.0,Varies with device,1.000000e+09,Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
2604,Instagram,SOCIAL,4.5,66577446.0,Varies with device,1.000000e+09,Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
2611,Instagram,SOCIAL,4.5,66577313.0,Varies with device,1.000000e+09,Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
3909,Instagram,SOCIAL,4.5,66509917.0,Varies with device,1.000000e+09,Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device

In [16]:
#Identify all app names with non-ascii characters
index = 0
for b in df.App.iloc[:8718]: # or .iloc[:5]
    count = 0
    for character in b:
        if ord(character) > 127:
            count += 1
            if count > 3:
                df.iloc[index,0] = 'non-ascii'
                print(b)
    index +=1

Flame - درب عقلك يوميا
Flame - درب عقلك يوميا
Flame - درب عقلك يوميا
Flame - درب عقلك يوميا
Flame - درب عقلك يوميا
Flame - درب عقلك يوميا
Flame - درب عقلك يوميا
Flame - درب عقلك يوميا
Flame - درب عقلك يوميا
သိင်္ Astrology - Min Thein Kha BayDin
သိင်္ Astrology - Min Thein Kha BayDin
РИА Новости
РИА Новости
РИА Новости
РИА Новости
РИА Новости
РИА Новости
РИА Новости
صور حرف H
صور حرف H
صور حرف H
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
L.POINT - 엘포인트 [ 포인트, 멤버십, 적립, 사용, 모바일 카드, 쿠폰, 롯데]
Al Quran Free - القرآن (Islam)
Al Quran Free - القرآن (Islam)
Al Quran Free - القرآن (Islam)
日本AV历史
বাংলা টিভি প্রো BD Bangla TV
বাংলা টিভি প্রো BD Bangla TV
বাংলা টিভি প্রো BD Bangla TV
বাংলা টিভি প্রো BD Bangla TV
বাংলা টিভি প্রো BD Bangla TV
বাংলা টিভি প্রো BD Bangla TV
বাংলা টিভি প্রো BD Bangla TV
বাংলা টিভি প্রো BD Bangla TV
বাংলা টিভি প্রো BD Bangla TV
বাংলা টিভি প্রো BD Bangla TV
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
BL 女性向け恋愛ゲーム◆俺プリクロス
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
SecondSecret ‐「恋を読む」BLノベルゲーム‐
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
BL 女性向け恋愛ゲーム◆ごくメン
あなカレ【BL】無料ゲーム
あなカレ【BL】無料ゲーム
あなカレ【BL】無料ゲーム
あなカレ【BL】無料ゲーム
あなカレ【BL】無料ゲーム
あなカレ【BL】無料ゲーム
あなカレ【BL】無料ゲーム
あなカレ【BL】無料ゲーム
감성학원 BL 첫사랑
감성학원 BL 첫사랑
감성학원 BL 첫사랑
감성학원 BL 첫사랑
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BQ-መጽሐፍ ቅዱሳዊ ጥያቄዎች
BS Calendar / Patro / पात्रो
BS Calendar / Patro / पात्रो
BS Calendar / Patro / पात्रो
Offline Jízdní řády CG Transit
CK 初一 十五
الفاتحون Conquerors
الفاتحون Conquerors
الفاتحون Conquerors
الفاتحون Conquerors
الفاتحون Conquerors
DG ग्राम / Digital Gram Panchayat
DG ग्राम / Digital Gram Panchayat
DW فارسی By dw-arab.com
DW فارسی By dw-arab.com
لعبة تقدر تربح DZ
لعبة تقدر تربح DZ
لعبة تقدر تربح DZ
لعبة تقدر تربح DZ
لعبة تقدر تربح DZ
لعبة تقدر تربح DZ
لعبة تقدر تربح DZ
لعبة تقدر تربح DZ
لعبة تقدر تربح DZ
বাংলাflix
বাংলাflix
英漢字典 EC Dictionary
ECナビ×シュフー
ECナビ×シュフー
ECナビ×シュフー
ECナビ×シュフー
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
أحداث وحقائق | خبر عاجل في اخبار العالم
EG SIM CARD (EGSIMCARD, 이지심카드)
EG SIM CARD (EGSIMCARD, 이지심카드)
Ey Sey Storytime រឿងនិទានតាឥសី
Ey Sey Storytime រឿងនិទានតាឥសី
Ey Sey Storytime រឿងនិទានតាឥសី
Ey Sey Storytime រឿងនិទានតាឥសី
Ey Sey Storytime រឿងនិទានតាឥសី
Ey Sey Storytime រឿងនិទានតាឥសី
Ey Sey Storytime រឿងនិទានតាឥសី
Ey Sey Storytime រឿងនិទានតាឥសី
Ey Sey Storytime រឿងនិទានតាឥសី
Ey Sey Storytime រឿងនិទានតាឥសី
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей
FP Разбитый дисплей

In [17]:
#Print out the non-ascii app names to check
df[df.App == 'non-ascii']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
710,non-ascii,EDUCATION,4.6,56065.0,37M,1000000.0,Free,0,Everyone,Education,"July 26, 2018",3.3,4.1 and up
1592,non-ascii,LIFESTYLE,4.7,2225.0,15M,100000.0,Free,0,Everyone,Lifestyle,"July 26, 2018",4.2.1,4.0.3 and up
3750,non-ascii,NEWS_AND_MAGAZINES,4.5,44274.0,8.0M,1000000.0,Free,0,Everyone,News & Magazines,"August 6, 2018",4.0.6,4.4 and up
4193,non-ascii,ART_AND_DESIGN,4.4,13.0,4.5M,1000.0,Free,0,Everyone,Art & Design,"March 27, 2018",2.0,4.0.3 and up
4324,non-ascii,LIFESTYLE,4.0,45224.0,49M,5000000.0,Free,0,Everyone,Lifestyle,"August 1, 2018",6.5.1,4.1 and up
5346,non-ascii,BOOKS_AND_REFERENCE,4.7,1777.0,23M,50000.0,Free,0,Everyone,Books & Reference,"February 15, 2015",1.1,2.2 and up
5698,non-ascii,BOOKS_AND_REFERENCE,4.1,215.0,30M,10000.0,Free,0,Teen,Books & Reference,"March 6, 2018",1.2,4.0 and up
6006,non-ascii,FAMILY,4.3,193.0,14M,10000.0,Free,0,Everyone,Entertainment,"April 29, 2017",1.3,4.0 and up
6406,non-ascii,FAMILY,4.2,3379.0,62M,100000.0,Free,0,Mature 17+,Simulation,"March 23, 2017",1.6.3,2.3.3 and up
6415,non-ascii,GAME,4.4,1563.0,40M,50000.0,Free,0,Teen,Adventure,"June 29, 2017",1.3.6,4.0 and up
6417,non-ascii,FAMILY,4.2,1901.0,8.2M,100000.0,Free,0,Mature 17+,Simulation,"July 7, 2016",1.3.0,2.3.3 and up
6418,non-ascii,FAMILY,4.7,6073.0,8.5M,100000.0,Free,0,Mature 17+,Simulation,"February 25, 2018",4.2.2,2.3 and up
6420,non-ascii,COMICS,4.4,190.0,34M,10000.0,Free,0,Everyone,Comics,"November 17, 2017",3.2.1,3.0 and up
6629,non-ascii,GAME,4.7,191.0,7.2M,5000.0,Free,0,Everyone,Trivia,"July 31, 2018",4.1.2,4.1 and up
6729,non-ascii,PRODUCTIVITY,4.2,218.0,Varies with device,50000.0,Free,0,Everyone,Productivity,"July 15, 2018",Varies with device,Varies with device
7290,non-ascii,MAPS_AND_NAVIGATION,4.6,7314.0,7.0M,100000.0,Free,0,Everyone,Maps & Navigation,"September 7, 2017",3.1.4,4.0 and up
7463,non-ascii,LIFESTYLE,4.0,294.0,153k,10000.0,Free,0,Everyone,Lifestyle,"July 3, 2013",1.0.12,2.1 and up
7751,non-ascii,FAMILY,4.5,108130.0,40M,5000000.0,Free,0,Teen,Strategy,"August 3, 2018",1.8.0,4.0 and up
8394,non-ascii,NEWS_AND_MAGAZINES,4.5,53.0,5.9M,10000.0,Free,0,Teen,News & Magazines,"June 19, 2018",1.7,4.0 and up
8994,non-ascii,NEWS_AND_MAGAZINES,4.7,11.0,4.4M,1000.0,Free,0,Everyone,News & Magazines,"March 26, 2017",1.0.0,4.1 and up
9117,non-ascii,FAMILY,4.2,238.0,6.8M,10000.0,Free,0,Everyone,Education,"November 18, 2016",6.0.0.0,4.1 and up
9200,non-ascii,FAMILY,4.2,1111.0,7.3M,100000.0,Free,0,Everyone,Entertainment,"June 5, 2018",3.6.1,4.1 and up
9222,non-ascii,FAMILY,4.3,55408.0,Varies with device,1000000.0,Free,0,Everyone,Education,"January 8, 2018",Varies with device,Varies with device
9248,non-ascii,LIFESTYLE,4.0,576.0,7.4M,50000.0,Free,0,Everyone,Lifestyle,"June 7, 2018",1.0.2,4.0 and up
9308,non-ascii,NEWS_AND_MAGAZINES,4.8,311.0,14M,5000.0,Free,0,Everyone 10+,News & Magazines,"July 15, 2018",2.9.19a,4.2 and up
9317,non-ascii,BUSINESS,2.9,322.0,1.5M,50000.0,Free,0,Everyone,Business,"March 28, 2017",2.13,2.2 and up
10098,non-ascii,FAMILY,4.7,1327.0,44M,10000.0,Free,0,Everyone,Education;Education,"May 18, 2017",1.2.2,4.0.3 and up
10763,non-ascii,FAMILY,4.5,922.0,552k,50000.0,Free,0,Everyone,Entertainment,"September 20, 2014",1.1,1.6 and up

In [18]:
#Re-assign the dataframe and filter out teh non-ascii app names
df = df[df.App != 'non-ascii']
df.describe()

            Rating       Reviews      Installs
count  8691.000000  8.691000e+03  8.691000e+03
mean      4.185652  5.528608e+05  1.927747e+07
std       0.512643  3.260456e+06  9.457560e+07
min       1.000000  1.000000e+00  1.000000e+00
25%       4.000000  2.370000e+02  1.000000e+04
50%       4.300000  7.885000e+03  1.000000e+06
75%       4.500000  9.791250e+04  5.000000e+06
max       5.000000  7.815831e+07  1.000000e+09

In [21]:
#Remove duplicate apps by retaining the app with the highest number of installs
#dfnonduplicates = df.groupby('App')['Installs'].max() 
#print(dfnonduplicates)

App
+Download 4 Instagram Twitter                                                                                                         1000000.0
- Free Comics - Comic Apps                                                                                                              10000.0
.R                                                                                                                                      10000.0
/u/app                                                                                                                                  10000.0
058.ba                                                                                                                                    100.0
1. FC Köln App                                                                                                                         100000.0
10 Best Foods for You                                                                                                                  500000.0
10 Minutes a Day Times Tables                                                                                                          100000.0
100 Doors of Revenge                                                                                                                 10000000.0
100+ C Programs                                                                                                                          5000.0
100000+ Messages - DP, Status, Jokes & GIF 2018                                                                                         10000.0
101 C Programming Problems                                                                                                              50000.0
104 Looking for a job - looking for a job, looking for a job, looking for a part-time job, health checkup, resume, treatment room     1000000.0
11st                                                                                                                                 10000000.0
12 Step Meditations & Sober Prayers AA NA AL-ANON                                                                                       50000.0
1800 Contacts - Lens Store                                                                                                            1000000.0
1LINE – One Line with One Touch                                                                                                      10000000.0
2-Player Co-op Zombie Shoot                                                                                                              1000.0
20 Minuten (CH)                                                                                                                       1000000.0
20 minutes (CH)                                                                                                                       1000000.0
2000 AD Comics and Judge Dredd                                                                                                          50000.0
2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif                                                                                     10000000.0
2019 Tricks Es File Explores                                                                                                             1000.0
2048 BTS J Hope KPop Puzzle Game                                                                                                         1000.0
2048(AI)                                                                                                                                 1000.0
21-Day Meditation Experience                                                                                                           100000.0
211:CK Lite                                                                                                                                10.0
24 megapixel hd camera                                                                                                                 100000.0
24/7 BZ Reis                                                                                                                           100000.0
2Date Dating App, Love and matching                                                                                                    500000.0
                                                                                                                                        ...
usgang.ch                                                                                                                              100000.0
v-view                                                                                                                                  10000.0
vide-greniers.org                                                                                                                      100000.0
video player                                                                                                                          1000000.0
video player for android                                                                                                             10000000.0
view.com.au - Buy, Rent or Research Real Estate                                                                                         50000.0
virtual lover 3D                                                                                                                       100000.0
w UN map                                                                                                                              1000000.0
waut.ch!                                                                                                                                  100.0
weather - weather forecast                                                                                                            1000000.0
weight conversion calculator                                                                                                           100000.0
wetter.com - Weather and Radar                                                                                                       10000000.0
wikiHow: how to do anything                                                                                                           1000000.0
yHomework - Math Solver                                                                                                               1000000.0
zulily - Shop Daily Deals in Fashion and Home                                                                                         1000000.0
¡Ay Metro!                                                                                                                              10000.0
¿Es Vegan?                                                                                                                              10000.0
ÖBB Scotty                                                                                                                            1000000.0
İşCep                                                                                                                                10000000.0
Šmelina .cz inzeráty inzerce                                                                                                            10000.0
Аim Training for CS                                                                                                                    100000.0
РееI Smart Remote MP3 CD Player                                                                                                          5000.0
► MultiCraft ― Free Miner! 👍                                                                                                         50000000.0
【Miku AR Camera】Mikuture                                                                                                              1000000.0
乐屋网: Buying a house, selling a house, renting a house                                                                                  100000.0
乗換NAVITIME　Timetable & Route Search in Japan Tokyo                                                                                    5000000.0
漫咖 Comics - Manga,Novel and Stories                                                                                                   1000000.0
💘 WhatsLov: Smileys of love, stickers and GIF                                                                                         1000000.0
📏 Smart Ruler ↔️ cm/inch measuring for homework!                                                                                        10000.0
🔥 Football Wallpapers 4K | Full HD Backgrounds 😍                                                                                      1000000.0
Name: Installs, Length: 7566, dtype: float64

In [20]:
#Calculate average number of installs per application in each category
dfAvg = df.groupby('Category')['Installs'].sum() / df.groupby('Category')['Installs'].count()
dfAvg

Category
ART_AND_DESIGN         2.141657e+06
AUTO_AND_VEHICLES      7.372194e+05
BEAUTY                 6.408619e+05
BOOKS_AND_REFERENCE    1.143577e+07
BUSINESS               3.440912e+06
COMICS                 9.829140e+05
COMMUNICATION          1.066859e+08
DATING                 1.383634e+06
EDUCATION              5.798333e+06
ENTERTAINMENT          1.951673e+07
EVENTS                 3.544313e+05
FAMILY                 6.488859e+06
FINANCE                2.827183e+06
FOOD_AND_DRINK         2.558110e+06
GAME                   3.444470e+07
HEALTH_AND_FITNESS     5.552573e+06
HOUSE_AND_HOME         2.218184e+06
LIBRARIES_AND_DEMO     9.551231e+05
LIFESTYLE              1.819253e+06
MAPS_AND_NAVIGATION    6.135987e+06
MEDICAL                1.991946e+05
NEWS_AND_MAGAZINES     3.301845e+07
PARENTING              6.472085e+05
PERSONALIZATION        9.393095e+06
PHOTOGRAPHY            3.372664e+07
PRODUCTIVITY           4.269461e+07
SHOPPING               1.376196e+07
SOCIAL                 5.474644e+07
SPORTS                 5.891878e+06
TOOLS                  1.706259e+07
TRAVEL_AND_LOCAL       3.150769e+07
VIDEO_PLAYERS          3.988350e+07
WEATHER                6.254191e+06
Name: Installs, dtype: float64